[package]
name = "orly"
version = "0.1.0"
edition = "2018"
authors = ["hurlenko"]
description = "Download O'Reilly books as EPUB"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["json", "cookies", "gzip"] }
url = "2.2.2"
tokio = { version = "1", features = ["full"] }
serde = "1.0.126"
anyhow = "1.0.42"
thiserror = "1.0.26"
chrono = "0.4.19"
libxml = "0.3.0"
futures = "0.3.15"
askama = "0.10.5"
bytes = "1.0.1"
zip = "0.5.13"
lazy_static = "1.4.0"
clap = "3.0.0-beta.4"
sanitize-filename = "0.3.0"
